- PILIH FOLDER INPUT
- PILIH FOLDER OUTPUT
- AKSI KE TIGA MENJADI RENAME & GENERATE SUMMARY
- URUT BERDASARKAN PROJECT DATE
- WARNING JIKA PROJECT ID SAMA, BERI TAMPILKAN.
- FORMAT GANTI KE XLSX

RENAME FILE:
- PCM P1051 2025 CUST1